<?php

namespace Database\Seeders;

use App\Models\Ebook;
use Illuminate\Database\Seeder;

class EbookSeeder extends Seeder
{
    public function run(): void
    {
        $ebooks = [
            [
                'id' => 1,
                'title' => 'Laravel: Up & Running',
                'slug' => 'laravel-up-running',
                'description' => 'A complete guide to the Laravel PHP framework. Learn to build modern web applications with Laravel from the ground up. Covers routing, Eloquent ORM, Blade templating, queues, and more.',
                'author' => 'Matt Stauffer',
                'price' => 80000.00,
                'cover_image' => null,
                'file_path' => 'ebooks/LRxiXFYVXPSdlXwMrteeAxF0qPQiMWkws1BDc6qn.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 13:57:08',
                'updated_at' => '2026-05-20 14:58:28',
            ],
            [
                'id' => 2,
                'title' => 'Clean Code',
                'slug' => 'clean-code',
                'description' => 'Clean Code adalah panduan praktis untuk menulis kode yang bersih dan mudah dipelihara.',
                'author' => 'Robert C. Martin',
                'price' => 120000.00,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/41SH-SvWPxL.jpg',
                'file_path' => 'ebooks/vAOrje3itFHBdeI5jBwF48qLXl82dcaX74Ffa45m.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 13:57:08',
                'updated_at' => '2026-05-20 14:53:38',
            ],
            [
                'id' => 3,
                'title' => 'The Pragmatic Programmer',
                'slug' => 'the-pragmatic-programmer',
                'description' => 'Your Journey to Mastery. This book will help you become a better programmer. Topics range from personal responsibility to career development, and include architectural techniques to keep code flexible.',
                'author' => 'David Thomas & Andrew Hunt',
                'price' => 110000.00,
                'cover_image' => null,
                'file_path' => 'ebooks/rWDS4vZ743Wwt8yH8aao60ue5frpxQa6UxODVAlv.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 13:57:08',
                'updated_at' => '2026-05-20 14:55:42',
            ],
            [
                'id' => 4,
                'title' => 'JavaScript: The Good Parts',
                'slug' => 'javascript-the-good-parts',
                'description' => 'Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad. This book identifies the goodness in JavaScript that makes it work well.',
                'author' => 'Douglas Crockford',
                'price' => 99000.00,
                'cover_image' => null,
                'file_path' => 'ebooks/GSo4eMMlfnxTEnisK0dFxKXC4NU75Vn8Sury0HBE.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 13:57:08',
                'updated_at' => '2026-05-20 14:56:32',
            ],
            [
                'id' => 5,
                'title' => 'Python Crash Course',
                'slug' => 'python-crash-course',
                'description' => 'Pengantar Python praktis dengan proyek nyata.',
                'author' => 'Eric Matthes',
                'price' => 115000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781593279288-L.jpg',
                'file_path' => 'ebooks/fy0nfkZbhR5BUY11RBIkNMikEX4qG9maMOd2urZq.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 13:57:08',
                'updated_at' => '2026-05-20 15:37:10',
            ],
            [
                'id' => 6,
                'title' => 'Design Patterns',
                'slug' => 'design-patterns',
                'description' => 'Pola desain klasik untuk software berorientasi objek.',
                'author' => 'Erich Gamma et al.',
                'price' => 135000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg',
                'file_path' => 'ebooks/OcUW6r7r00AmU0ItP0TBMiD2xH0LlHEiPhUtl2ef.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 13:57:08',
                'updated_at' => '2026-05-20 14:59:40',
            ],
            [
                'id' => 7,
                'title' => 'CSS: The Definitive Guide',
                'slug' => 'css-the-definitive-guide',
                'description' => 'If you\'re a web designer or app developer interested in sophisticated page styling, improved accessibility, and saving time and effort, this comprehensive guide is essential reading.',
                'author' => 'Eric A. Meyer',
                'price' => 90000.00,
                'cover_image' => null,
                'file_path' => 'ebooks/gQMXsteGXOAK4ZAK4WgZI8QG3nicFQvFLkmYe5Md.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 13:57:08',
                'updated_at' => '2026-05-20 15:10:02',
            ],
            [
                'id' => 8,
                'title' => 'Domain-Driven Design',
                'slug' => 'domain-driven-design',
                'description' => 'Tackling Complexity in the Heart of Software. This is not a book about specific technologies. It\'s about how you think about the problems you\'re solving.',
                'author' => 'Eric Evans',
                'price' => 145000.00,
                'cover_image' => null,
                'file_path' => 'ebooks/uiGPjk4BDwU9XdcdLiBAnJKyCGZloQClZhNQ4sT4.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 13:57:08',
                'updated_at' => '2026-05-21 03:22:24',
            ],
            [
                'id' => 9,
                'title' => 'Laut Bercerita',
                'slug' => 'laut-bercerita',
                'description' => 'Laut Bercerita adalah novel yang mengisahkan perjuangan, kehilangan, dan harapan di masa penuh gejolak.',
                'author' => 'Leila S. Chudori',
                'price' => 97000.00,
                'cover_image' => 'laut-bercerita.jpeg',
                'file_path' => 'ebooks/SvPsFVaf5IzLFXGQohCKZNBZxVdHJDT9sxCOLY4P.pdf',
                'category' => 'Novel',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 16:00:18',
            ],
            [
                'id' => 10,
                'title' => 'Atomic Habits',
                'slug' => 'atomic-habits',
                'description' => 'Atomic Habits menjelaskan bagaimana perubahan kecil yang konsisten dapat membentuk hasil besar.',
                'author' => 'James Clear',
                'price' => 0.00,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg',
                'file_path' => 'ebooks/TTlKikyTS7LEJWwFEvcJzjHKA8weMsiFbUOQg8qd.pdf',
                'category' => 'Pengembangan Diri',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:27:14',
            ],
            [
                'id' => 11,
                'title' => 'Sapiens',
                'slug' => 'sapiens',
                'description' => 'Sapiens membahas evolusi manusia dari masa purba hingga modern.',
                'author' => 'Yuval Noah Harari',
                'price' => 135000.00,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg',
                'file_path' => 'ebooks/KvQKPux60nOrPkJmy8AXD5oi6VhPmvVm9Kab3TnL.pdf',
                'category' => 'Sejarah',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:31:55',
            ],
            [
                'id' => 12,
                'title' => 'Psychology of Money',
                'slug' => 'psychology-of-money',
                'description' => 'Psychology of Money mengeksplorasi bagaimana orang berpikir tentang uang.',
                'author' => 'Morgan Housel',
                'price' => 0.00,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71g2ednj0JL.jpg',
                'file_path' => 'ebooks/s1vgGowWQCPxvTZK4CyyU30eR8oWzbmCnseC8ZHW.pdf',
                'category' => 'Bisnis',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:34:57',
            ],
            [
                'id' => 13,
                'title' => 'Mindset',
                'slug' => 'mindset',
                'description' => 'Mindset menjelaskan perbedaan antara fixed mindset dan growth mindset.',
                'author' => 'Carol S. Dweck',
                'price' => 0.00,
                'cover_image' => 'mindset.jpeg',
                'file_path' => 'ebooks/0l4PLP1jIJlmNXHLccMFszYCSq4gGQcDQJBM38gl.pdf',
                'category' => 'Pengembangan Diri',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:29:53',
            ],
            [
                'id' => 14,
                'title' => 'Dune',
                'slug' => 'dune',
                'description' => 'Kisah epik di gurun Arrakis tentang kekuasaan, takdir, dan perebutan rempah.',
                'author' => 'Frank Herbert',
                'price' => 118000.00,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/91uwocAMtSL.jpg',
                'file_path' => 'ebooks/bj3J1tPPXrTG9eavoNmmWn3zprLqfqVZPJp1oCaV.pdf',
                'category' => 'Fiksi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:30:45',
            ],
            [
                'id' => 15,
                'title' => 'The Alchemist',
                'slug' => 'the-alchemist',
                'description' => 'Novel reflektif tentang keberanian mengikuti mimpi dan menemukan tujuan pribadi.',
                'author' => 'Paulo Coelho',
                'price' => 84000.00,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg',
                'file_path' => 'ebooks/x9DUIIPxG2Z5CJ8ACaexFpGt4xjizA2KB2HgWkWX.pdf',
                'category' => 'Fiksi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:33:22',
            ],
            [
                'id' => 16,
                'title' => 'The Midnight Library',
                'slug' => 'the-midnight-library',
                'description' => 'Kisah emosional tentang kemungkinan hidup yang berbeda, penyesalan, dan harapan.',
                'author' => 'Matt Haig',
                'price' => 92000.00,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81J6APjwxlL.jpg',
                'file_path' => 'ebooks/YXkKp8XgNLUdhXQOr3eVDAVXs1p81olWhlQJ6XVF.pdf',
                'category' => 'Fiksi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:34:26',
            ],
            [
                'id' => 17,
                'title' => 'Ikigai',
                'slug' => 'ikigai',
                'description' => 'Rahasia hidup panjang dan bahagia dari Jepang melalui tujuan dan kebiasaan kecil.',
                'author' => 'Hector Garcia',
                'price' => 88000.00,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81l3rZK4lnL.jpg',
                'file_path' => 'ebooks/Z6rH9XAPfNnBPSFPET6Qz7SKuQBY14ihlhQXpGBW.pdf',
                'category' => 'Pengembangan Diri',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:35:34',
            ],
            [
                'id' => 18,
                'title' => 'Norwegian Wood',
                'slug' => 'norwegian-wood',
                'description' => 'Novel tentang memori, kehilangan, dan masa muda.',
                'author' => 'Haruki Murakami',
                'price' => 89000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780375704024-L.jpg',
                'file_path' => 'ebooks/ofrYiv6TLPGejNDVosH6tKcafRMERmWcNBG2Hbf4.pdf',
                'category' => 'Fiksi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:36:11',
            ],
            [
                'id' => 19,
                'title' => 'Pulang',
                'slug' => 'pulang',
                'description' => 'Kisah keluarga, perjalanan, dan pulang pada makna hidup.',
                'author' => 'Tere Liye',
                'price' => 49000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9786020822129-L.jpg',
                'file_path' => 'ebooks/AKASZx2Wmoc7k1smgcRpZYs2EDTIQL2rC31CubAn.pdf',
                'category' => 'Seri Novel',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:36:55',
            ],
            [
                'id' => 21,
                'title' => 'Rich Dad Poor Dad',
                'slug' => 'rich-dad-poor-dad',
                'description' => 'Pelajaran dasar tentang aset, uang, dan cara berpikir finansial.',
                'author' => 'Robert T. Kiyosaki',
                'price' => 79000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg',
                'file_path' => 'ebooks/BiAz6TwK6f9lM9SMlyPiHQijAppyTnsMrFHymoTr.pdf',
                'category' => 'Ekonomi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:38:20',
            ],
            [
                'id' => 22,
                'title' => 'Thinking, Fast and Slow',
                'slug' => 'thinking-fast-and-slow',
                'description' => 'Cara kerja pikiran manusia dalam mengambil keputusan.',
                'author' => 'Daniel Kahneman',
                'price' => 110000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg',
                'file_path' => 'ebooks/TqFzniS9r74dyA3YPQwqAdRz0lTf8lV6tglOx33q.pdf',
                'category' => 'Pendidikan',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:38:50',
            ],
            [
                'id' => 23,
                'title' => 'Deep Work',
                'slug' => 'deep-work',
                'description' => 'Panduan fokus mendalam di tengah distraksi digital.',
                'author' => 'Cal Newport',
                'price' => 85000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg',
                'file_path' => 'ebooks/gyptoQ9cGTnRypZyP4k7cJrLlUmk8pjibHXJ4qd2.pdf',
                'category' => 'Motivasi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:39:20',
            ],
            [
                'id' => 24,
                'title' => 'Start With Why',
                'slug' => 'start-with-why',
                'description' => 'Mengapa tujuan yang jelas membuat organisasi lebih kuat.',
                'author' => 'Simon Sinek',
                'price' => 88000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg',
                'file_path' => 'ebooks/vwJWs4cGvCnCvD6pE1fJxo386Mlk2zrDfSGT42RW.pdf',
                'category' => 'Motivasi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:43:40',
            ],
            [
                'id' => 25,
                'title' => 'Zero to One',
                'slug' => 'zero-to-one',
                'description' => 'Cara membangun perusahaan dan produk yang benar-benar baru.',
                'author' => 'Peter Thiel',
                'price' => 82000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg',
                'file_path' => 'ebooks/azzQcMmv2BBcDaB1Ab2KF7GLPau4KIuwrdVGhyft.pdf',
                'category' => 'Bisnis',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:41:04',
            ],
            [
                'id' => 26,
                'title' => 'Good to Great',
                'slug' => 'good-to-great',
                'description' => 'Riset tentang perusahaan yang berubah dari baik menjadi hebat.',
                'author' => 'Jim Collins',
                'price' => 98000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg',
                'file_path' => 'ebooks/GqsSuUQeJ3Dm54jbrBt004klllIRcwZOMEZXELXV.pdf',
                'category' => 'Bisnis',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:42:32',
            ],
            [
                'id' => 27,
                'title' => 'The Lean Startup',
                'slug' => 'the-lean-startup',
                'description' => 'Metode membangun bisnis dengan eksperimen cepat.',
                'author' => 'Eric Ries',
                'price' => 92000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg',
                'file_path' => 'ebooks/4F2pMR30KxJSPp8EauXi83eWIVoZlxDziWRCPrM1.pdf',
                'category' => 'Bisnis',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:44:29',
            ],
            [
                'id' => 28,
                'title' => 'Economics in One Lesson',
                'slug' => 'economics-in-one-lesson',
                'description' => 'Pengantar ekonomi klasik yang ringkas dan tajam.',
                'author' => 'Henry Hazlitt',
                'price' => 75000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780517548233-L.jpg',
                'file_path' => 'ebooks/hOZMo5fvTQ8oEKTC6daem1Id9SU67OyI4p6iZNkf.pdf',
                'category' => 'Ekonomi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:45:09',
            ],
            [
                'id' => 29,
                'title' => 'Freakonomics',
                'slug' => 'freakonomics',
                'description' => 'Melihat ekonomi dari sudut pandang yang tidak biasa.',
                'author' => 'Steven D. Levitt',
                'price' => 86000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780060731335-L.jpg',
                'file_path' => 'ebooks/rX6vpztB4Kzs6ib8Ho6Wpnp2oP7T8k9dsoA9JaSV.pdf',
                'category' => 'Ekonomi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:45:52',
            ],
            [
                'id' => 30,
                'title' => 'Capital in the Twenty-First Century',
                'slug' => 'capital-in-the-twenty-first-century',
                'description' => 'Kajian ketimpangan dan kapital dalam ekonomi modern.',
                'author' => 'Thomas Piketty',
                'price' => 145000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780674430006-L.jpg',
                'file_path' => 'ebooks/K6jtLz7OdPuOD8kbYFDTVHqPfVTkaTJLBDADfe3g.pdf',
                'category' => 'Ekonomi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:49:10',
            ],
            [
                'id' => 31,
                'title' => 'Clean Architecture',
                'slug' => 'clean-architecture',
                'description' => 'Prinsip arsitektur perangkat lunak yang tahan perubahan.',
                'author' => 'Robert C. Martin',
                'price' => 125000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780134494166-L.jpg',
                'file_path' => 'ebooks/MIvbD3N0Y3EZJ4jZiJvHDywn7b3VEykF2hDlLmBQ.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:54:53',
            ],
            [
                'id' => 32,
                'title' => 'JavaScript: The Good Parts',
                'slug' => 'javascript-the-good-parts-1',
                'description' => 'Bagian terbaik JavaScript untuk menulis kode yang lebih baik.',
                'author' => 'Douglas Crockford',
                'price' => 99000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780596517748-L.jpg',
                'file_path' => 'ebooks/DAMfox0gOVcu4J4nkjnR2KQFAeljZJZKn0cekDIl.pdf',
                'category' => 'Teknologi',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:47:53',
            ],
            [
                'id' => 33,
                'title' => 'Breath',
                'slug' => 'breath',
                'description' => 'Sains dan praktik bernapas untuk kesehatan.',
                'author' => 'James Nestor',
                'price' => 88000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780735213616-L.jpg',
                'file_path' => 'ebooks/6JxFra8CQYRg6tt9bUb10kCZwbMUaMiKFChnXMlA.pdf',
                'category' => 'Kesehatan',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:49:49',
            ],
            [
                'id' => 34,
                'title' => 'Why We Sleep',
                'slug' => 'why-we-sleep',
                'description' => 'Mengapa tidur penting untuk tubuh dan pikiran.',
                'author' => 'Matthew Walker',
                'price' => 96000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781501144318-L.jpg',
                'file_path' => 'ebooks/vLXKyPR2DwQPZmuRN0Kwy2ehCWwTnl2vesEMq5FH.pdf',
                'category' => 'Kesehatan',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:50:53',
            ],
            [
                'id' => 35,
                'title' => 'The Body Keeps the Score',
                'slug' => 'the-body-keeps-the-score',
                'description' => 'Hubungan trauma, tubuh, dan proses pemulihan.',
                'author' => 'Bessel van der Kolk',
                'price' => 105000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780143127741-L.jpg',
                'file_path' => 'ebooks/RoMBGadHelmBSjIOpJjbdw42pahdWNpm6vCleaY9.pdf',
                'category' => 'Kesehatan',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:51:28',
            ],
            [
                'id' => 36,
                'title' => 'Outlive',
                'slug' => 'outlive',
                'description' => 'Strategi hidup panjang dan sehat berbasis sains.',
                'author' => 'Peter Attia',
                'price' => 132000.00,
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780593236598-L.jpg',
                'file_path' => 'ebooks/KaYsdAe5YfUiOCcRCbybqUTI15JKwM3w8dPZCNJn.pdf',
                'category' => 'Kesehatan',
                'status' => 'published',
                'created_at' => '2026-05-16 14:53:55',
                'updated_at' => '2026-05-20 14:52:01',
            ],
            [
                'id' => 45,
                'title' => 'HUJAN',
                'slug' => 'hujan',
                'description' => 'NOVEL ROMANCE BEST SELLER',
                'author' => 'TERE LIYE',
                'price' => 150000.00,
                'cover_image' => 'covers/Iz92CQfDVD1y6UI14EpVv4qe61T5gN5zuKYhMOCe.jpg',
                'file_path' => 'ebooks/9B81GMi91zszS0PkjuYeTHCJsYvQ94fxilt41qqX.pdf',
                'category' => 'Novel',
                'status' => 'published',
                'created_at' => '2026-05-19 16:32:07',
                'updated_at' => '2026-05-19 16:32:53',
            ],
        ];

        foreach ($ebooks as $ebookData) {
            Ebook::updateOrCreate(['id' => $ebookData['id']], $ebookData);
        }
    }
}
